# fly.toml app configuration file generated for file-sharing-v1-holy-field-13 on 2025-11-27T15:46:17+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'file-sharing-v1-holy-field-13'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'


  [build.secrets]
    DATABASE_URL = "env:DATABASE_URL"

[env]
  HTTP_SERVER_ADDRESS = '0.0.0.0:8080'
  DATABASE_URL = ""

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '5s'
    grace_period = '5s'

[checks]
  [checks.status]
    type = 'http'
    interval = '30s'
    timeout = '5s'
    grace_period = '5s'
    method = 'get'
    path = '/api/health'
    protocol = 'http'

[[vm]]
  size = 'shared-cpu-1x'
  processes = ['app']

[[metrics]]
  port = 9090
  path = '/metrics'
